-   id: cairo-lint
    name: check lint cairo
    description: checks lint of contracts using amarna
    entry: check-lint
    language: python

-   id: cairo-format
    name: check format cairo
    description: checks formatting of contracts using cairo-format
    entry: check-format
    language: python